### ISSUE TITLE
There is an error executing the tests

### ISSUE THREAD

**Issue by DemonOFmooN** [Murrengan/murr_back#12]
There are two errors in the tests, screenshots are attached.

![FileNotFoundError](https://user-images.githubusercontent.com/11556107/75615344-1880f200-5b4b-11ea-8000-7fcd07a8883c.png)

![ValueError](https://user-images.githubusercontent.com/11556107/75615348-1f0f6980-5b4b-11ea-8779-53164aa87e42.png)

**Comment by Murrengan** [comment]
fixed. test and close issues pls
